server:
  port: 8080

spring:
  datasource:
    username: nys
    password: pass1234
    url: jdbc:mysql://localhost:3306/supportportal
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect